### ISSUE TITLE
jest --env=jsdom TypeError: TextDecoder is not a constructor

### ISSUE THREAD

**Issue by lidel** [Gozala/web-encoding#10] opened 2020-11-09 22:53 UTC
`jest` with `--env=jsdom`  fails with `TypeError: TextDecoder is not a constructor`

@Gozala did not dig into it, but I assume this is a bug: it is fair to expect people use `js-multiaddr` (which depends on web-encoding) in apps tested with jest.

That's what we do in ipfs-webui – see below.

## How to reproduce

Having below in `multibase/src/util.js` causes jest-based tests to fail in ipfs-webui:

- example in PR: https://github.com/ipfs-shipyard/ipfs-webui/pull/1689
  - failed job: https://app.circleci.com/pipelines/github/ipfs-shipyard/ipfs-webui/708/workflows/ce65ef3d-3ba5-4b2f-8cab-9352d49fd458/jobs/4738

```
const { TextEncoder, TextDecoder } = require('web-encoding')
const textDecoder = new TextDecoder()     
```

```
 FAIL  src/bundles/analytics.test.js
  ● Test suite failed to run

    TypeError: TextDecoder is not a constructor

    > 1 | import multiaddr from 'multiaddr'
        | ^
      2 | // @ts-ignore
      3 | import HttpClient from 'ipfs-http-client'
      4 | // @ts-ignore

      at Object.<anonymous> (node_modules/uint8arrays/node_modules/multibase/src/util.js:6:21)
      at Object.<anonymous> (node_modules/uint8arrays/node_modules/multibase/src/base.js:4:24)
      at Object.<anonymous> (node_modules/uint8arrays/node_modules/multibase/src/constants.js:5:14)
      at Object.<anonymous> (node_modules/uint8arrays/to-string.js:3:19)
```

**Comment by Gozala** [comment] 2020-11-09 23:17
@lidel this seems like the same issue as https://github.com/Gozala/web-encoding/issues/1#issuecomment-676811667 do you mind checking if the same workaround works in this context as well ?

**Comment by dannyhchan** [comment] 2021-04-16 19:19
Getting error when using it in the latest create web app with node v15.4.0.  Does anyone know how to resolve this?

![textDecoder-error](https://user-images.githubusercontent.com/8468808/115074003-1a308500-9ec7-11eb-8fcc-bd079e53127c.png)


System:
OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
Binaries:
Node: 15.4.0 - ~/.nvm/versions/node/v15.4.0/bin/node
Yarn: 1.17.3 - /usr/bin/yarn
npm: 7.0.15 - ~/.nvm/versions/node/v15.4.0/bin/npm

**Comment by ghost** [comment] 2021-04-20 03:12
> Getting error when using it in the latest create web app with node v15.4.0. Does anyone know how to resolve this?
> 
> ![textDecoder-error](https://user-images.githubusercontent.com/8468808/115074003-1a308500-9ec7-11eb-8fcc-bd079e53127c.png)
> 
> System:
> OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
> CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
> Binaries:
> Node: 15.4.0 - ~/.nvm/versions/node/v15.4.0/bin/node
> Yarn: 1.17.3 - /usr/bin/yarn
> npm: 7.0.15 - ~/.nvm/versions/node/v15.4.0/bin/npm

hi, have you solved it?

**Comment by dannyhchan** [comment] 2021-04-20 03:38
@mandyJiai no, I was not able to solve it.  It seems that the issue was caused by using the ipfs-http-client library.  Instead of using that library, I switched to using ipfs-api which still worked for my use case.

**Comment by Gozala** [comment] 2021-04-20 03:42
@mandyJiai @dannyhchan as described in in this comment https://github.com/Gozala/web-encoding/issues/1#issuecomment-676811667 issue is caused by jest and jsdom combination and not this library. It can be fixed by updating jest.

**Closed as completed by Gozala** 2021-04-20 03:42 UTC
